// <auto-generated />
namespace StudentsManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migration1FullNameCancel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration1FullNameCancel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050956114_Migration1FullNameCancel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
